version: '2'

services:

  frontend:
    build: frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - oracle_backend_celltower
    links:
      - oracle_backend_celltower

  oracle_backend_celltower:
    build: oracle/backendOracle
    container_name: backend_celltower
    ports:
      - "5000:5000"

  backend:
    build: backend
    container_name: backend
    ports:
      - "4000:4000"
    depends_on:
      - testrpc_server
    links:
      - testrpc_server

  testrpc_server:
    build: testrpc
    container_name: testrpc
    ports:
      - "8545:8545"

  db :
    build: db
    container_name: db
    ports:
      - "5432:5432"

  s2 :
    build: oracle/s2-server
    container_name: s2-server
    ports:
      - "8180:8180"